### ISSUE TITLE
I don't understand why the model.weight.weight is prototype to calculate the dense loss

### ISSUE THREAD

**Issue by Dylanbron** [seongmin-kye/MCT#10]
# pixel-wise classification
        key_DC = key[nb_class * self.n_shot:]
        key_DC = key_DC.reshape(key_DC.size(0), key_DC.size(1), -1)
        key_DC = key_DC.permute(0, 2, 1)
        **prototype = self.model.weight.weight**
        loss_dense = 0
        distance = key_DC.unsqueeze(2) - prototype
        distance = distance.pow(2).sum(dim=3)
        for i in range(distance.size(1)):
            loss_dense += self.loss(-distance[:,i], labels_DC[nb_class * self.n_shot:])/distance.size(1)

I don't understand why the model.weight.weight is prototype to calculate the dense loss
Would you mind explain this for me? Thank you very much.

**Comment by seongmin-kye** [comment]
Dense classifier is regularizer for the instance-wise embeddings. As Lifchitz et al [1] doing, we set the global prototype as prevariable parameters.
