### ISSUE TITLE
Is this also code for the paper Transductive Few-shot Learning with Meta-Learned Confidence?

### ISSUE THREAD

**Issue by SnowyJune973** [seongmin-kye/MCT#11]
Greetings!
I found your paper _Transductive Few-shot Learning with Meta-Learned Confidence_ on arXiv 2002.12017 (which is quite a fascinating idea), and followed the link in it and was redirected to this repository. I wonder if this is also the code repository for MCT-DFMN? Looks like there's nothing related to DFMN in the code.

**Comment by seongmin-kye** [comment]
Hi!
Codes are slightly changed.

Thanks!

**Comment by seongmin-kye** [comment]
I re-upload the previous version of this paper.
[https://github.com/seongmin-kye/MCT_DFMN](url)

Thanks

**Comment by SnowyJune973** [comment]
> I re-upload the previous version of this paper.
> [https://github.com/seongmin-kye/MCT_DFMN](url)
> 
> Thanks

Thanks a lot! You're really helpful
