### ISSUE TITLE
issue about the preprocessing 

### ISSUE THREAD

**Issue by CSer-Tang-hao** [seongmin-kye/MCT#12]
I noticed that the operation similar to "transforms. Normalize" is not used in data preprocessing, but this is a common data processing step that used in most previous works such as MetaOptNet.

Looking forward to your reply!

 Thanks

**Comment by seongmin-kye** [comment]
I think that normalization step is not suitable for practical scenarios, since training data and classes can be incremental. But, normalization with mean & std should know data statistics.

Thanks.

**Comment by CSer-Tang-hao** [comment]
> I think that normalization step is not suitable for practical scenarios, since training data and classes can be incremental. But, normalization with mean & std should know data statistics.
> 
> Thanks.

In terms of the use of the normalization step, have you done any experiments to show that it's affecting?

**Comment by seongmin-kye** [comment]
I haven't experimented separately. It would be great if you could try and let me know.
